# Dependabot configuration for Vulnetix
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates weekly
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Reviewers for npm pull requests
    reviewers:
      - "vulnetix/team"
    # Labels on npm pull requests
    labels:
      - "dependencies"
      - "npm"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for GitHub Actions
    open-pull-requests-limit: 10
    # Reviewers for GitHub Actions pull requests
    reviewers:
      - "vulnetix/team"
    # Labels on GitHub Actions pull requests
    labels:
      - "dependencies"
      - "github-actions"
